config/routes.rb
require 'access_constraints'

Rails.application.routes.draw do

    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    match '/signout', to: 'sessions#destroy', via: [:get, :post]
    get '/dashboard', to: 'devs#dashboard', via: [:get]
    get '/terms', to: 'static#terms'

    namespace :access, defaults: { format: :json } do
        scope module: :v1, contraints: AccessConstraints.new(version: 1, default: true) do
            resources :users
            match '/users/search', to: 'users#search', via: [:post]
            match '/users/check', to: 'users#check', via: [:post]
        end
    end

    resources :devs
    resources :apps
    match '/create_app', to: 'apps#create', via: [:post]

    root 'static#home'

end

app/models/dev.rb
class Dev < ActiveRecord::Base

    before_create :create_remember_token

    has_many :identities, inverse_of: :dev, dependent: :destroy
    has_many :apps, inverse_of: :dev, dependent: :destroy

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 50}
    validates :access_level, presence: true

    def Dev.new_remember_token
        SecureRandom.urlsafe_base64
    end

    def Dev.digest(token)
        Digest::SHA1.hexdigest(token.to_s)
    end

    def Dev.create_with_omniauth(info)
        create(name: info['name'])
    end

    private

    def create_remember_token
        self.remember_token = Dev.digest(Dev.new_remember_token)
    end
end

app/controllers/devs_controller.rb
class DevsController < ApplicationController

  def dashboard
      @apps = App.where("dev_id=?", current_dev.id)
  end

  def new
  end

end

app/helpers/dev_helper.rb
module DevHelper
end

app/views/devs/dashboard.html.erb
<% content_for :title do%>
    Dashboard
<% end %>

<% content_for :title_content do%>
    My Dashboard
<% end %>

<div class="dashboard_div">
    <div class="dashboard_content">
        <div class="new_app_button_div">
        <%= link_to(new_app_path) do %>
            <button type="button" id="new_app_button" class="btn btn-default"> + New App </button>
        <% end %>
        </div>
        <div class="apps_display_div container">
            <div class="title_span">My Apps: </div>
            <% @apps.each do |app|%>
                <%= link_to(app_path(app)) do %>
                    <div class="mini_app_display col-xs-3 col-md-3">
                        <div class="mini_property">App Name : <%= app.name %> </div>
                        <div class="mini_property">App Access Level : <%= app.access_level %></div>
                    </div>
                <% end %>
                    <div class="empty_display col-xs-1 col-md-1"></div>
            <% end %>
        </div>
    </div>
</div>

app/views/devs/new.html.erb
<%= render 'shared/sidebar' %>

You are a new developer. Enjoy our features.