config/routes.rb
require 'access_constraints'

Rails.application.routes.draw do

    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    match '/signout', to: 'sessions#destroy', via: [:get, :post]
    get '/dashboard', to: 'devs#dashboard', via: [:get]
    get '/terms', to: 'static#terms'

    namespace :access, defaults: { format: :json } do
        scope module: :v1, contraints: AccessConstraints.new(version: 1, default: true) do
            resources :users
            match '/users/search', to: 'users#search', via: [:post]
            match '/users/check', to: 'users#check', via: [:post]
        end
    end

    resources :devs
    resources :apps
    match '/create_app', to: 'apps#create', via: [:post]

    root 'static#home'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class=" navbar_container container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <%= link_to(root_path) do %>
            <b class="navbar-brand">IITM Alumni Access</b>
    <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggdivng -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <% if signed_in? %>
                    <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Settings<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li class="navbar_link"><a href="#">Profile*</a></li>
                    <li class="divider"></li>
                    <li class="navbar_link"><%= link_to "Sign Out", signout_path %></li>
                </ul>
                </li>
            <% else %>
                <li class="navbar_link"><a data-toggle="modal" data-target="#signin_modal" href="#">Sign In</a></li>
            <% end %>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
    <div class="sidebar_list">
        <div id="welcome" class="sidelist_element">Welcome, <%= signed_in? ? current_dev.name : "Guest" %>! </div>    
        <% if signed_in? %>
            <div class="sidelist_element"><%= link_to(dashboard_path) do %><div class="sidebar_link">Dashboard</div><% end %></div> 
        <% else %>
        <% end %>
        <div class="sidelist_element"><%= link_to('#') do %><div class="sidebar_link">Dummy Link 1</div><% end %></div> 
        <div class="sidelist_element"><%= link_to('#') do %><div class="sidebar_link">Dummy Link 2</div><% end %></div> 
        <div class="sidelist_element"><%= link_to('#') do %><div class="sidebar_link">Dummy Link 3</div><% end %></div> 
    </div>
</div>

app/views/shared/_signin_modal.html.erb
<div id="signin_modal" class=" modal fade" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Please sign in using one of the following services:</h4>
            </div>
            <div class="modal-body">
                <a href="/auth/google_oauth2/">
                <div id="gSignInWrapper">
                    <span class="label"></span>
                    <div id="customBtn" class="customGPlusSignIn">
                        <span class="icon google_icon"></span>
                        <span class="buttonText">Sign In with Google</span>
                    </div>
                </div>
                </a>
                <br>
                <a href="/auth/facebook/">
                <div id="fSignInWrapper">
                    <span class="label"></span>
                    <div id="customBtn" class="customFacebookSignIn">
                        <span class="icon facebook_icon"></span>
                        <span class="buttonText">Sign In with Facebook</span>
                    </div>
                </div>
                </a>
            </div>
            <div class="modal-footer">
                <p class="center_align">By Signing in, you agree to our <%= link_to "Terms and Conditions", terms_path%>.</p>
            </div>
        </div>

    </div>
</div>