config/routes.rb
require 'access_constraints'

Rails.application.routes.draw do

    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    match '/signout', to: 'sessions#destroy', via: [:get, :post]
    get '/dashboard', to: 'devs#dashboard', via: [:get]
    get '/terms', to: 'static#terms'

    namespace :access, defaults: { format: :json } do
        scope module: :v1, contraints: AccessConstraints.new(version: 1, default: true) do
            resources :users
            match '/users/search', to: 'users#search', via: [:post]
            match '/users/check', to: 'users#check', via: [:post]
        end
    end

    resources :devs
    resources :apps
    match '/create_app', to: 'apps#create', via: [:post]

    root 'static#home'

end

app/views/apps/_app.html.erb
<div class="container_fluid app_div">
    <div class="col-md-3 col-xs-3">
        <div class="row app_element_property">App Name</div>
        <div class="row app_element_property">App Secret ID</div>
        <div class="row app_element_property">App Secret Key</div>
        <div class="row app_element_property">App Access Level</div>
    </div>
    <div class="col-md-9 col-xs-9">
        <div class="row app_element_value"><%= app.name %></div>
        <div class="row app_element_value"><%= app.secret_id %></div>
        <div class="row app_element_value"><%= app.secret_key %></div>
        <div class="row app_element_value"><%= app.access_level %></div>
    </div>
</div>

app/views/apps/new.html.erb
<% content_for :title do%>
    Create New App
<% end %>

<% content_for :title_content do%>
    Create New App
<% end %>

<div class="new_app_form">
    <div class="form_container">
        <div class="row no_margin">
            <div class="span6 offset3">
                <%= form_for(:app, url: create_app_path, method: 'post' , :html => { :class => "form-horizontal"}) do |f| %>

                    <%= f.text_field :name , class:"form-control", placeholder:"App Name" %><br>
                    <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
            <% end %>
            </div>
        </div>
    </div>
</div>

app/views/apps/show.html.erb
<% content_for :title do%>
    <%= @app.name %>
<% end %>

<% content_for :title_content do%>
    My Apps > <%= @app.name %>
<% end %>

<div class="app_show_div">
    <%= render @app %>
</div>

<div class="app_setting">
    Settings
</div>